<a href="https://colab.research.google.com/github/jitendra986/100-Days-of-Deep-Learning/blob/main/backpropagation_classification_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2,activation = 'sigmoid', input_dim =2))
model.add(Dense(1,activation = 'sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[ 1.2078887 , -0.15765512],
        [-0.10728586, -0.09737825]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2633773],
        [ 1.0148212]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:

new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(loss='binary_crossentropy', optimizer = optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 1s 5ms/step - loss: 0.6940
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 3/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6939
Epoch 4/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 5/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 6/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 7/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6939
Epoch 10/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 11/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 12/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 13/50
4/4 [==============================] - 0s 3ms/step - loss: 0.