<a href="https://colab.research.google.com/github/jitendra986/100-Days-of-Deep-Learning/blob/main/backpropagation_regression_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df



cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation='linear', input_dim=2)) # hidden 2 units
model.add(Dense(1,activation='linear')) # hidden 1 units

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.get_weights()

[array([[-0.47345573,  0.65609396],
        [-0.2835009 , -1.1603199 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.3165387 ],
        [-0.29715824]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [13]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss='mean_squared_error', optimizer = optimizer)

In [18]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 150ms/step - loss: 27.8737
Epoch 2/75
4/4 [==============================] - 0s 5ms/step - loss: 27.5524
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2374
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 26.8953
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 26.5561
Epoch 6/75
4/4 [==============================] - 0s 6ms/step - loss: 26.1742
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 25.8229
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4340
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0472
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 24.6215
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 24.2333
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8020
Epoch 13/75
4/4 [==============================] - 0s 4ms/s

In [19]:
model.get_weights()

[array([[0.37330976, 0.37330976],
        [0.36550155, 0.36550155]], dtype=float32),
 array([0.27211905, 0.27211905], dtype=float32),
 array([[0.37271568],
        [0.37271568]], dtype=float32),
 array([0.20480332], dtype=float32)]